version: '3'
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "5001:5000"
    environment:
      - NODE_ID=node1
      - PEERS=node2,node3

  node2:
    build: .
    container_name: node2
    ports:
      - "5002:5000"
    environment:
      - NODE_ID=node2
      - PEERS=node1,node3

  node3:
    build: .
    container_name: node3
    ports:
      - "5003:5000"
    environment:
      - NODE_ID=node3
      - PEERS=node1,node2